#ifndef HTTPSTATUSCODE_HPP
#define HTTPSTATUSCODE_HPP

#define HTTP_STATUS_OK  200
#define HTTP_STATUS_CREATED 201
#define HTTP_STATUS_NO_CONTENT  204

#define HTTP_STATUS_MULTIPLE_CHOICES 300
#define HTTP_STATUS_MOVED_PERMANENTLY 301
#define HTTP_STATUS_FOUND 302

#define HTTP_STATUS_BAD_REQUEST 400
#define HTTP_STATUS_FORBIDDEN 403
#define HTTP_STATUS_NOT_FOUND 404
#define HTTP_STATUS_METHOD_NOT_ALLOWED 405
#define HTTP_STATUS_REQUEST_ENTITY_TOO_LARGE 413

#define HTTP_STATUS_INTERNAL_SERVER_ERROR 500
#define HTTP_STATUS_NOT_IMPLEMENTED 501
#define HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED 505

#endif
